name: CI

on:
  pull_request:
    branches: [main]
  push:

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build
